CREATE TABLE IF NOT EXISTS "schema_migrations" ("version" INTEGER PRIMARY KEY, "inserted_at" TEXT);
CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "email" TEXT NOT NULL COLLATE NOCASE, "hashed_password" TEXT, "confirmed_at" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, "nombre_completo" TEXT NOT NULL, "rol" TEXT NOT NULL, "activo" INTEGER DEFAULT true);
CREATE TABLE sqlite_sequence(name,seq);
CREATE UNIQUE INDEX "users_email_index" ON "users" ("email");
CREATE TABLE IF NOT EXISTS "users_tokens" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "user_id" INTEGER NOT NULL CONSTRAINT "users_tokens_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "token" BLOB NOT NULL, "context" TEXT NOT NULL, "sent_to" TEXT, "authenticated_at" TEXT, "inserted_at" TEXT NOT NULL);
CREATE INDEX "users_tokens_user_id_index" ON "users_tokens" ("user_id");
CREATE UNIQUE INDEX "users_tokens_context_token_index" ON "users_tokens" ("context", "token");
CREATE TABLE IF NOT EXISTS "settings" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre" TEXT NOT NULL, "descripcion" TEXT, "fecha_inicio" TEXT, "fecha_fin" TEXT, "ubicacion" TEXT, "direccion_evento" TEXT, "logo" TEXT, "estado" TEXT NOT NULL, "inscripciones_abiertas" INTEGER DEFAULT false, "info_turismo" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "attendee_categories" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre" TEXT, "codigo" TEXT, "precio" DECIMAL, "color" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "attendee_categories_codigo_index" ON "attendee_categories" ("codigo");
CREATE TABLE IF NOT EXISTS "speakers" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre_completo" TEXT, "biografia" TEXT, "institucion" TEXT, "foto" TEXT, "email" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "rooms" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre" TEXT, "capacidad" INTEGER, "ubicacion" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "sessions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "titulo" TEXT, "descripcion" TEXT, "fecha" TEXT, "hora_inicio" TEXT, "hora_fin" TEXT, "tipo" TEXT, "speaker_id" INTEGER CONSTRAINT "sessions_speaker_id_fkey" REFERENCES "speakers"("id") ON DELETE SET NULL, "room_id" INTEGER CONSTRAINT "sessions_room_id_fkey" REFERENCES "rooms"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "sessions_speaker_id_index" ON "sessions" ("speaker_id");
CREATE INDEX "sessions_room_id_index" ON "sessions" ("room_id");
CREATE INDEX "sessions_fecha_index" ON "sessions" ("fecha");
CREATE TABLE IF NOT EXISTS "commissions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre" TEXT, "codigo" TEXT, "encargado_id" INTEGER CONSTRAINT "commissions_encargado_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "commissions_codigo_index" ON "commissions" ("codigo");
CREATE INDEX "commissions_encargado_id_index" ON "commissions" ("encargado_id");
CREATE TABLE IF NOT EXISTS "commission_operators" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "commission_id" INTEGER CONSTRAINT "commission_operators_commission_id_fkey" REFERENCES "commissions"("id") ON DELETE CASCADE, "user_id" INTEGER CONSTRAINT "commission_operators_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "commission_operators_commission_id_user_id_index" ON "commission_operators" ("commission_id", "user_id");
CREATE INDEX "commission_operators_commission_id_index" ON "commission_operators" ("commission_id");
CREATE INDEX "commission_operators_user_id_index" ON "commission_operators" ("user_id");
CREATE TABLE IF NOT EXISTS "attendees" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre_completo" TEXT, "numero_documento" TEXT, "email" TEXT, "telefono" TEXT, "institucion" TEXT, "foto" TEXT, "comprobante_pago" TEXT, "codigo_qr" TEXT, "imagen_qr" TEXT, "credencial_digital" TEXT, "token_descarga" TEXT, "estado" TEXT, "fecha_revision" TEXT, "motivo_rechazo" TEXT, "credencial_entregada" INTEGER DEFAULT false NOT NULL, "fecha_entrega_credencial" TEXT, "material_entregado" INTEGER DEFAULT false NOT NULL, "fecha_entrega_material" TEXT, "sesiones_asistidas" INTEGER, "category_id" INTEGER CONSTRAINT "attendees_category_id_fkey" REFERENCES "attendee_categories"("id") ON DELETE CASCADE, "revisado_por" INTEGER CONSTRAINT "attendees_revisado_por_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "quien_entrego_credencial" INTEGER CONSTRAINT "attendees_quien_entrego_credencial_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "quien_entrego_material" INTEGER CONSTRAINT "attendees_quien_entrego_material_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "attendees_token_descarga_index" ON "attendees" ("token_descarga");
CREATE UNIQUE INDEX "attendees_codigo_qr_index" ON "attendees" ("codigo_qr");
CREATE UNIQUE INDEX "attendees_email_index" ON "attendees" ("email");
CREATE UNIQUE INDEX "attendees_numero_documento_index" ON "attendees" ("numero_documento");
CREATE INDEX "attendees_category_id_index" ON "attendees" ("category_id");
CREATE INDEX "attendees_revisado_por_index" ON "attendees" ("revisado_por");
CREATE INDEX "attendees_quien_entrego_credencial_index" ON "attendees" ("quien_entrego_credencial");
CREATE INDEX "attendees_quien_entrego_material_index" ON "attendees" ("quien_entrego_material");
CREATE TABLE IF NOT EXISTS "meals" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "nombre" TEXT, "tipo" TEXT, "fecha" TEXT, "hora_desde" TEXT, "hora_hasta" TEXT, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "meals_fecha_index" ON "meals" ("fecha");
CREATE TABLE IF NOT EXISTS "meal_deliveries" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "fecha_entrega" TEXT, "attendee_id" INTEGER CONSTRAINT "meal_deliveries_attendee_id_fkey" REFERENCES "attendees"("id") ON DELETE CASCADE, "meal_id" INTEGER CONSTRAINT "meal_deliveries_meal_id_fkey" REFERENCES "meals"("id") ON DELETE CASCADE, "entregado_por" INTEGER CONSTRAINT "meal_deliveries_entregado_por_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "meal_deliveries_attendee_id_meal_id_index" ON "meal_deliveries" ("attendee_id", "meal_id");
CREATE INDEX "meal_deliveries_attendee_id_index" ON "meal_deliveries" ("attendee_id");
CREATE INDEX "meal_deliveries_meal_id_index" ON "meal_deliveries" ("meal_id");
CREATE INDEX "meal_deliveries_entregado_por_index" ON "meal_deliveries" ("entregado_por");
CREATE TABLE IF NOT EXISTS "session_attendances" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "fecha_escaneo" TEXT, "attendee_id" INTEGER CONSTRAINT "session_attendances_attendee_id_fkey" REFERENCES "attendees"("id") ON DELETE CASCADE, "session_id" INTEGER CONSTRAINT "session_attendances_session_id_fkey" REFERENCES "sessions"("id") ON DELETE CASCADE, "escaneado_por" INTEGER CONSTRAINT "session_attendances_escaneado_por_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "session_attendances_attendee_id_session_id_index" ON "session_attendances" ("attendee_id", "session_id");
CREATE INDEX "session_attendances_attendee_id_index" ON "session_attendances" ("attendee_id");
CREATE INDEX "session_attendances_session_id_index" ON "session_attendances" ("session_id");
CREATE INDEX "session_attendances_escaneado_por_index" ON "session_attendances" ("escaneado_por");
CREATE TABLE IF NOT EXISTS "certificates" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "codigo_verificacion" TEXT, "archivo_pdf" TEXT, "porcentaje_asistencia" DECIMAL, "sesiones_asistidas" INTEGER, "total_sesiones" INTEGER, "fecha_generacion" TEXT, "attendee_id" INTEGER CONSTRAINT "certificates_attendee_id_fkey" REFERENCES "attendees"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE UNIQUE INDEX "certificates_codigo_verificacion_index" ON "certificates" ("codigo_verificacion");
CREATE UNIQUE INDEX "certificates_attendee_id_index" ON "certificates" ("attendee_id");
CREATE TABLE IF NOT EXISTS "email_logs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "tipo_email" TEXT, "destinatario" TEXT, "fecha_envio" TEXT, "estado" TEXT, "attendee_id" INTEGER CONSTRAINT "email_logs_attendee_id_fkey" REFERENCES "attendees"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "email_logs_attendee_id_index" ON "email_logs" ("attendee_id");
CREATE INDEX "email_logs_tipo_email_index" ON "email_logs" ("tipo_email");
CREATE INDEX "email_logs_fecha_envio_index" ON "email_logs" ("fecha_envio");
CREATE TABLE IF NOT EXISTS "audit_logs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "accion" TEXT, "tipo_recurso" TEXT, "id_recurso" INTEGER, "cambios" TEXT, "fecha_accion" TEXT, "user_id" INTEGER CONSTRAINT "audit_logs_user_id_fkey" REFERENCES "users"("id") ON DELETE CASCADE, "inserted_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL);
CREATE INDEX "audit_logs_user_id_index" ON "audit_logs" ("user_id");
CREATE INDEX "audit_logs_accion_index" ON "audit_logs" ("accion");
CREATE INDEX "audit_logs_fecha_accion_index" ON "audit_logs" ("fecha_accion");
CREATE INDEX "attendees_estado_index" ON "attendees" ("estado");
CREATE INDEX "attendees_fecha_revision_index" ON "attendees" ("fecha_revision");
CREATE INDEX "attendees_fecha_entrega_credencial_index" ON "attendees" ("fecha_entrega_credencial");
CREATE INDEX "attendees_fecha_entrega_material_index" ON "attendees" ("fecha_entrega_material");
CREATE INDEX "attendees_sesiones_asistidas_index" ON "attendees" ("sesiones_asistidas");
CREATE INDEX "attendees_estado_category_id_index" ON "attendees" ("estado", "category_id");
CREATE INDEX "meal_deliveries_fecha_entrega_index" ON "meal_deliveries" ("fecha_entrega");
CREATE INDEX "meal_deliveries_entregado_por_fecha_entrega_index" ON "meal_deliveries" ("entregado_por", "fecha_entrega");
CREATE INDEX "session_attendances_fecha_escaneo_index" ON "session_attendances" ("fecha_escaneo");
CREATE INDEX "session_attendances_escaneado_por_fecha_escaneo_index" ON "session_attendances" ("escaneado_por", "fecha_escaneo");
CREATE INDEX "audit_logs_user_id_accion_index" ON "audit_logs" ("user_id", "accion");
CREATE INDEX "audit_logs_tipo_recurso_id_recurso_index" ON "audit_logs" ("tipo_recurso", "id_recurso");
CREATE INDEX "audit_logs_fecha_accion_accion_index" ON "audit_logs" ("fecha_accion", "accion");
CREATE INDEX "email_logs_tipo_email_estado_index" ON "email_logs" ("tipo_email", "estado");
CREATE INDEX "email_logs_fecha_envio_tipo_email_index" ON "email_logs" ("fecha_envio", "tipo_email");
CREATE INDEX "certificates_fecha_generacion_index" ON "certificates" ("fecha_generacion");
CREATE INDEX "certificates_attendee_id_fecha_generacion_index" ON "certificates" ("attendee_id", "fecha_generacion");
CREATE INDEX "users_rol_index" ON "users" ("rol");
CREATE INDEX "users_activo_index" ON "users" ("activo");
CREATE INDEX "users_rol_activo_index" ON "users" ("rol", "activo");
CREATE INDEX "sessions_hora_inicio_index" ON "sessions" ("hora_inicio");
CREATE INDEX "sessions_hora_fin_index" ON "sessions" ("hora_fin");
CREATE INDEX "sessions_fecha_hora_inicio_index" ON "sessions" ("fecha", "hora_inicio");
CREATE INDEX "rooms_capacidad_index" ON "rooms" ("capacidad");
CREATE INDEX "speakers_institucion_index" ON "speakers" ("institucion");
CREATE INDEX "attendee_categories_precio_index" ON "attendee_categories" ("precio");
INSERT INTO schema_migrations VALUES(20251016012620,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016012808,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016012915,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013211,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013253,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013306,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013324,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013400,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013410,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013425,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013439,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013455,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013523,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013558,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013607,'2025-10-16T21:25:41');
INSERT INTO schema_migrations VALUES(20251016013617,'2025-10-16T23:03:12');
INSERT INTO schema_migrations VALUES(20251016020000,'2025-10-16T23:03:12');
