defmodule YachanakuyWeb.ErrorHTML do
  @moduledoc """
  This module is invoked by your endpoint in case of errors on HTML requests.

  See config/config.exs.
  """
  use YachanakuyWeb, :html

  embed_templates "error_html/*"

  # The render function is automatically generated by embed_templates
  # but we can override specific templates if needed
end
